name: train_random_forrest
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - wandb=0.13.10
  - hydra-core=1.0.6
  - mlflow=2.2.2
  - scikit-learn=1.2.1
  - matplotlib==3.7.1
  - pillow=9.4.0
  - pip=23.0.1
  - pip:
      - hydra-joblib-launcher==1.2.0

